version: '2'
services:
	elastic-1:
		image: "godois/clustered-elasticsearch-docker-image"
		ports:
			- "9201:9200"
			- "5601:5601"
		environment:
		    - CLUSTER_NAME: "sage-content"
		    - NODE_NAME: "sage-content-node1"
		    - IS_MASTER_ELEGIBLE_NODE: "yes"
		    - IS_DATA_NODE: "yes"
		    - LOCK_MEMORY: "true"
			- ES_JAVA_OPTS: "-Xms512m -Xmx512m"
			- CLUSTER_NAME: "sage-content"
			- DISCOVERY_HOSTS: "[\"elastisearch-node1.example.com\",\"elastisearch-node2.example.com\",\"elastisearch-node3.example.com\"]"
        extra_hosts:
            - "elastisearch-node3.example.com:192.170.1.3"
            - "elastisearch-node2.example.com:192.170.1.2"