# ======================== Elasticsearch Configuration =========================

# ---------------------------------- Cluster -----------------------------------
cluster.name: CLUSTER_NAME

# ------------------------------------ Node ------------------------------------
node.name: NODE_NAME
node.master: IS_MASTER_ELEGIBLE_NODE
node.data: IS_DATA_NODE

# ----------------------------------- Paths ------------------------------------
path.data: /var/data/elasticsearch
path.logs: /var/log/elasticsearch

# ----------------------------------- Memory -----------------------------------
bootstrap.memory_lock: LOCK_MEMORY

# ---------------------------------- Network -----------------------------------
#network.host: NETWORK_HOST
network.host: 0.0.0.0

# --------------------------------- Discovery ----------------------------------
#discovery.zen.ping.unicast.hosts: UNICAST_HOSTS
#discovery.zen.minimum_master_nodes: MINIMUM_MASTER_NODES
discovery.zen.minimum_master_nodes: 1

#action.auto_create_index: .security, .monitoring*, .watches, .triggered_watches, .watcher-history*